name: uihub
description: "free flutter ui is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/uihub

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/uihub/_new/
  uses-material-design: true

topics:
  - uihub